up_transposition_dict = {
    'c': 'cis',
    'cis': 'd',
    'des': 'd',
    'd': 'dis',
    'es': 'e',
    'dis': 'e',
    'e': 'f',
    'fes': 'f',
    'f': 'fis',
    'eis': 'fis',
    'fis': 'g',
    'ges': 'g',
    'fisis': 'gis',
    'g': 'gis',
    'as': 'a',
    'gis': 'a',
    'a': 'b',
    'b': 'h',
    'ais': 'h',
    'h': 'c',
    'ces': 'c',
    'his': 'cis'
}

down_transposition_dict = {
    'c': 'h',
    'his': 'h',
    'h': 'b',
    'ces': 'b',
    'b': 'a',
    'ais': 'a',
    'a': 'as',
    'as': 'g',
    'gis': 'g',
    'g': 'ges',
    'fisis': 'fis',
    'fis': 'f',
    'ges': 'f',
    'f': 'e',
    'eis': 'e',
    'e': 'es',
    'fes': 'es',
    'es': 'd',
    'dis': 'd',
    'd': 'des',
    'des': 'c',
    'cis': 'c'
}